# spring MariaDB Connect
spring:
  datasource:
#    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward // DB 추가되면 변경
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward
    username: delgo
    password: Zlzl2022!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000 #30000ms
      maxLifetime: 290000 #1800000ms(30?). maria db ??? 28800? (8??) -> ?? 1???? ??
#      maximumPoolSize: 20 #?? 10
#      validationTimeout: 1000 #5000ms, connectionTimeout ?? ??? ?
  # data - jpa ??
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 12MB
  kafka:
     consumer:
        bootstrap-servers: localhost:9092 # 컨슈머 서버 주소
        group-id: tester
     producer:
        bootstrap-servers: localhost:9092 # 프로듀서 서버 주소

server:
  port: 8081

config:
#  driverLocation: C:\\chrome\\chromedriver.exe #Local
  driverLocation: /var/www/chrome/chromedriver #Dev