# spring MariaDB Connect
spring:
  profiles:
      active: dev
  datasource:
    username: delgo
    password: Zlzl2022!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000 #30000ms
      maxLifetime: 280000 #1800000ms(30?). maria db ??? 28800? (8??) -> ?? 1???? ??
      #      maximumPoolSize: 20 #?? 10
      #      validationTimeout: 1000 #5000ms, connectionTimeout ?? ???
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        # show_sql: true # 쿼리 출력 여부
        # format_sql: true # 쿼리 포맷팅 여부
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 55MB
  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # 컨슈머 서버 주소
      group-id: tester
    producer:
      bootstrap-servers: localhost:9092 # 프로듀서 서버 주소

server:
  port: 8081

# Swagger 설정
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: method # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**


---
spring:
  profiles: local
  data:
    mongodb:
      database: delgo_reward_develop
      uri: mongodb://delgo:Zlzl2022!@101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:9724/delgo_reward_develop

config:
  profiles: local
  driverLocation: C:\\chrome\\chromedriver.exe
  # 이동재(윈도우)
  photo-dir: C:\\testPhoto\\
  photo-url: C:\\testPhoto\\
  # 조현서(맥)
  #  photo-dir: /Users/hs/Desktop/testPhoto
  kakao:
    REDIRECT_URL: "https://www.test.delgo.pet/oauth/callback/kakao"
  classificationDir: src/main/resources/classification_data_set/classification_category.json
  cors-allow-url: http://localhost:3000

---
spring:
  profiles: dev
  data:
    mongodb:
      database: delgo_reward_develop
      uri: mongodb://delgo:Zlzl2022!@101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:9724/delgo_reward_develop

config:
  profiles: dev
  driverLocation: /var/www/chrome/chromedriver
  photo-dir: /var/www/reward-backend/
  photo-url: https://www.test.delgo.pet/images/
  kakao:
    REDIRECT_URL: "https://www.test.delgo.pet/oauth/callback/kakao"
  classificationDir: /var/www/reward-backend/WEB-INF/classes/classification_data_set/classification_category.json
  cors-allow-url: https://www.test.delgo.pet, http://localhost:3000

---
spring:
  profiles: real
  data:
    mongodb:
      database: delgo_reward
      uri: mongodb://delgo:Zlzl2022!@101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:9724/delgo_reward

config:
  profiles: real
  driverLocation: /var/www/chrome/chromedriver
  photo-dir: /var/www/reward-backend/
  photo-url: https://www.real.delgo.pet/images/
  kakao:
    REDIRECT_URL: "https://www.reward.delgo.pet/oauth/callback/kakao"
  classificationDir: /var/www/reward-backend/WEB-INF/classes/classification_data_set/classification_category.json
  cors-allow-url: https://www.reward.delgo.pet

---
spring:
  profiles: qa
  data:
    mongodb:
      database: delgo_reward_develop
      uri: mongodb://delgo:Zlzl2022!@101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:9724/delgo_reward_qa

config:
  profiles: qa
  driverLocation: /var/www/chrome/chromedriver
  photo-dir: /var/www/reward-backend/
  photo-url: https://www.qa.delgo.pet/images/
  kakao:
    REDIRECT_URL: "https://www.qa.delgo.pet/oauth/callback/kakao"
  classificationDir: /var/www/reward-backend/WEB-INF/classes/classification_data_set/classification_category.json
  cors-allow-url: https://www.qa.delgo.pet