# spring MariaDB Connect
spring:
  profiles:
    active: dev
  datasource:
    username: *************
    password: *************
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000 #30000ms
      maxLifetime: 290000 #1800000ms(30?). maria db ??? 28800? (8??) -> ?? 1???? ??
#      maximumPoolSize: 20 #?? 10
#      validationTimeout: 1000 #5000ms, connectionTimeout ?? ??? ?
  # data - jpa ??
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 12MB
  kafka:
     consumer:
        bootstrap-servers: localhost:9092 # 컨슈머 서버 주소
        group-id: tester
     producer:
        bootstrap-servers: localhost:9092 # 프로듀서 서버 주소

server:
  port: 8081

---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward_develop

config:
  driverLocation: C:\\chrome\\chromedriver.exe
  photoDir: C:\\testPhoto\\

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward_develop

config:
  driverLocation: /var/www/chrome/chromedriver
  photoDir: /var/www/reward-backend/


---
spring:
  profiles: real
  datasource:
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward

config:
  driverLocation: /var/www/chrome/chromedriver
  photoDir: /var/www/reward-backend/
