# spring MariaDB Connect
spring:
  profiles:
      active: local
  datasource:
    username: delgo
    password: Zlzl2022!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000 #30000ms
      maxLifetime: 280000 #1800000ms(30?). maria db ??? 28800? (8??) -> ?? 1???? ??
                          #      maximumPoolSize: 20 #?? 10
                          #      validationTimeout: 1000 #5000ms, connectionTimeout ?? ???
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 55MB
  kafka:
     consumer:
        bootstrap-servers: localhost:9092 # 컨슈머 서버 주소
        group-id: tester
     producer:
        bootstrap-servers: localhost:9092 # 프로듀서 서버 주소

server:
  port: 8081

---
spring:
  profiles: local
  data:
      mongodb:
        database: delgo_reward_develop
        uri: mongodb://101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward_develop

config:
  profiles: local
  driverLocation: C:\\chrome\\chromedriver.exe
  # 이동재(윈도우)
  photoDir: C:\\testPhoto\\
  # 조현서(맥)
#   photoDir: /Users/hs/Desktop/testPhoto
  kakao:
    REDIRECT_URL: "https://www.test.delgo.pet/oauth/callback/kakao"
  classificationDir: src/main/resources/classification_data_set/classification_category.json

---
spring:
  profiles: dev
  data:
        mongodb:
          database: delgo_reward_develop
          uri: mongodb://101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward_develop

config:
  profiles: dev
  driverLocation: /var/www/chrome/chromedriver
  photoDir: /var/www/reward-backend/
  kakao:
    REDIRECT_URL: "https://www.test.delgo.pet/oauth/callback/kakao"
  classificationDir: /var/www/reward-backend/WEB-INF/classes/classification_data_set/classification_category.json


---
spring:
  profiles: real
  data:
        mongodb:
          database: delgo_reward
          uri: mongodb://101.101.208.202:27017
  datasource:
    url: jdbc:mariadb://101.101.208.202:3306/delgo_reward

config:
  profiles: real
  driverLocation: /var/www/chrome/chromedriver
  photoDir: /var/www/reward-backend/
  kakao:
    REDIRECT_URL: "https://www.reward.delgo.pet/oauth/callback/kakao"
  classificationDir: /var/www/reward-backend/WEB-INF/classes/classification_data_set/classification_category.json